#!/usr/bin/env python3
"""
Honeytoken Detection Simulation Script
Tests the system's ability to detect when honeytokens are accessed
"""

import requests
import time
import random
import argparse
import sys
from urllib.parse import urljoin
import json
import uuid

def simulate_honeytoken_detection(proxy_url, iterations=15):
    """
    Simulates honeytoken detection by using known honeytokens in requests
    """
    print(f"Starting honeytoken detection simulation against {proxy_url}")
    
    # Known honeytokens generated by the deception module
    honeytokens = [
        'fake_api_key_' + str(uuid.uuid4()),
        'honey_user_' + str(uuid.uuid4()),
        'decoy_cred_' + str(uuid.uuid4()),
        'fake_token_' + str(uuid.uuid4()),
        'honeypot_endpoint_' + str(uuid.uuid4()),
        'fake_db_password_' + str(uuid.uuid4()),
        'canary_' + str(uuid.uuid4()) + '_record',
        'trap_credential_' + str(uuid.uuid4()),
        'decoy_' + str(uuid.uuid4()) + '_account',
        'fake_' + str(uuid.uuid4()) + '_session'
    ]
    
    # Headers to make requests appear more realistic
    headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36',
        'Accept': 'application/json, text/plain, */*',
        'Accept-Language': 'en-US,en;q=0.9',
        'Authorization': 'Bearer legitimate_user_token',
        'Content-Type': 'application/json',
    }
    
    # Endpoints that might trigger honeytoken hits
    endpoints = [
        '/api/auth/login',
        '/api/config/update',
        '/api/integrations/webhook',
        '/admin/settings',
        '/api/external/connect',
        '/api/services/register',
        '/api/oauth/token',
        '/api/database/connect',
        '/api/backup/restore',
        '/api/import/process',
        '/api/sync/data',
        '/api/transfer/initiate',
        '/api/hooks/receive',
        '/api/providers/authenticate',
        '/api/keys/rotate'
    ]
    
    detected_tokens = []
    
    for i in range(iterations):
        # Select random endpoint and honeytoken
        endpoint = random.choice(endpoints)
        honeytoken = random.choice(honeytokens)
        
        target_url = urljoin(proxy_url, endpoint)
        
        # Different ways to include honeytoken in the request
        token_usage_methods = [
            # As part of JSON payload
            lambda ht: {'apiKey': ht, 'service': 'external_integration'},
            # As URL parameter
            lambda ht: {'token': ht, 'action': 'authorize'},
            # As part of form data
            lambda ht: {'credentials': {'password': ht}},
            # As part of a larger data structure
            lambda ht: {'integration_config': {'auth_token': ht, 'endpoint': 'https://external.service.com/api'}}
        ]
        
        payload_method = random.choice(token_usage_methods)
        payload = payload_method(honeytoken)
        
        try:
            response = requests.post(target_url, headers=headers, json=payload, timeout=8)
            
            status = response.status_code
            print(f"Iteration {i+1}: POST {endpoint} with honeytoken -> {status}")
            
            # Check if the response indicates honeytoken detection
            # This would depend on how the proxy responds when detecting honeytoken usage
            response_text = response.text.lower()
            if any(indicator in response_text for indicator in ['honey', 'trap', 'decoy', 'suspicious', 'detected']):
                print(f"  [ALERT] Honeytoken {honeytoken} potentially detected!")
                detected_tokens.append(honeytoken)
            
            # Sometimes send the same token in headers too
            if random.random() > 0.4:
                header_variations = [
                    {'X-API-Key': honeytoken},
                    {'Authorization': f'Bearer {honeytoken}'},
                    {'X-Auth-Token': honeytoken},
                    {'API-Token': honeytoken}
                ]
                
                extra_headers = headers.copy()
                extra_header_set = random.choice(header_variations)
                extra_headers.update(extra_header_set)
                
                extra_response = requests.get(target_url, headers=extra_headers, timeout=8)
                print(f"  With honeytoken in header -> {extra_response.status_code}")
                
                extra_response_text = extra_response.text.lower()
                if any(indicator in extra_response_text for indicator in ['honey', 'trap', 'decoy', 'suspicious', 'detected']):
                    print(f"  [ALERT] Honeytoken {honeytoken} potentially detected in headers!")
                    if honeytoken not in detected_tokens:
                        detected_tokens.append(honeytoken)
            
            # Random delay to simulate real-world timing
            time.sleep(random.uniform(0.3, 1.2))
            
        except requests.exceptions.RequestException as e:
            print(f"Iteration {i+1}: Error accessing {endpoint} - {str(e)}")
    
    print(f"\nHoneytoken detection simulation completed.")
    print(f"Total honeytokens used: {len(set(honeytokens))}")
    print(f"Honeytokens potentially detected: {len(detected_tokens)}")
    if detected_tokens:
        print(f"Detected tokens: {', '.join(set(detected_tokens))}")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='Simulate honeytoken detection')
    parser.add_argument('--proxy-url', default='http://localhost:8080', help='Proxy URL (default: http://localhost:8080)')
    parser.add_argument('--iterations', type=int, default=15, help='Number of requests to send (default: 15)')
    
    args = parser.parse_args()
    
    simulate_honeytoken_detection(args.proxy_url, args.iterations)